name: Update VisitSaltLake CSV

on:
  schedule:
    - cron: "12 13 * * 1"   # every Monday 13:12 UTC (~07:12 America/Denver)
  workflow_dispatch: {}      # allow manual run from the Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas python-dateutil

      - name: Fetch & write CSV
        run: python scripts/vsl_to_csv.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/conventions.csv
            git commit -m "Update conventions.csv"
            git push
          else
            echo "No changes to commit."
          fi

